### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by jaygray0919** [hypermedia-app/shaperone#153]
this is a remarkable tool/service/capability.
it shows us how to do something we've struggled with for a while.
thank you for the building blocks.

**Comment by tpluscode** [comment]
Thank you @jaygray0919 for your kind words. I'm very glad you find shaperone useful. I hope you would actually use it in your projects. Let me know if I can help in any way

And if you're looking for inspiration, I will be more than happy to share my experience :)
