### ISSUE TITLE
Sample instances are not cleared from the Playground when adding custom shapes.

### ISSUE THREAD

**Issue by nicholsn** [hypermedia-app/shaperone#201]
I'm just getting acquainted with `shaperone` and want to thank you for you work on this project - it is extremely cool and fills a critical gap in the data-centric approach to model-driven UI. Truly, hats off to you! 

I've been using the playground to manually add in a custom shape and the form generation is working beautifully, but when I look at the data captured by the form it only includes the sample instances that are of a different type than the target class that I'm defining:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix schema: <http://schema.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .

<http://example.com/Jane_Doe> a schema:Person ;
	schema:name "Janet" .

<http://example.com/John_Doe> a schema:Person ;
	schema:name "John Doe" ;
	schema:age 17 ;
	schema:knows [
		rdf:type schema:Person ;
	] ;
	<http://id.mazetx.com/mio/hasAttribute> <http://id.mazetx.com/mio/AmyotrophicLateralSclerosis> ;
	<http://id.mazetx.com/mio/digitalObjectIdentifier> "http://mygwasstudy.com"^^xsd:anyURI ;
	<http://id.mazetx.com/mio/pValue> "0.0000123"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioLow> ".1"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioHigh> ".4"^^xsd:float ;
	<http://id.mazetx.com/mio/standardError> ".09"^^xsd:float .
``` 

Is there a way to clear out the sample instances and provide my own initial instance(s) that match the target class for the node shape I'm defining?

**Comment by nicholsn** [comment]
@tpluscode do you recommend sticking with the playground here or are there other examples where I could get started with a simple app?

**Comment by nicholsn** [comment]
Sure, here is a [link](https://forms.hypermedia.app/playground/#shapes=%40prefix+sh%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%40prefix+dash%3A+%3Chttp%3A%2F%2Fdatashapes.org%2Fdash%23%3E+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FGWASTraitAssociationShape%3E+a+sh%3ANodeShape+%3B%0A%09sh%3AtargetClass+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FGWASTraitAssociation%3E+%3B%0A%09%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E+%22GWAS+Trait+Association%22+%3B%0A%09sh%3Aproperty+%3Chttp%3A%2F%2Fexample.com%2FDigitalObjectIdentifierProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FTraitProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FPValueProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FOddsRatioProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FOddsRatioLowProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FOddsRatioHighProperty%3E%2C+%3Chttp%3A%2F%2Fexample.com%2FStandardErrorProperty%3E+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FDigitalObjectIdentifierProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FdigitalObjectIdentifier%3E+%3B%0A%09sh%3Aname+%22Digital+Object+Identifier%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23anyURI%3E+%3B%0A%09dash%3AsingleLine+true+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3Aorder+1+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FTraitProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FhasAttribute%3E+%3B%0A%09sh%3Aname+%22Trait%22+%3B%0A%09sh%3Aclass+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FTrait%3E+%3B%0A%09sh%3Amessage+%22Please+select+a+valid+trait%22+%3B%0A%09sh%3Ain+%28%0A%09%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FChronicKidneyDisease%3E%0A%09%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FAmyotrophicLateralSclerosis%3E%0A%09%29+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3Aorder+2+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FPValueProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FpValue%3E+%3B%0A%09sh%3Aname+%22P-Value%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3Aorder+3+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FOddsRatioProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FpValue%3E+%3B%0A%09sh%3Aname+%22Odds+Ratio%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3Aorder+4+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FOddsRatioLowProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FoddsRatioLow%3E+%3B%0A%09sh%3Aname+%22Odds+Ratio+Low%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3Aorder+5+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FOddsRatioHighProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FoddsRatioHigh%3E+%3B%0A%09sh%3Aname+%22Odds+Ratio+High%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3Aorder+6+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FStandardErrorProperty%3E+sh%3Apath+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FstandardError%3E+%3B%0A%09sh%3Aname+%22StandardError%22+%3B%0A%09sh%3Adatatype+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09sh%3AminCount+1+%3B%0A%09sh%3AmaxCount+1+%3B%0A%09sh%3Aorder+7+.%0A%0A%3Chttp%3A%2F%2Flexvo.org%2Fid%2Fiso639-1%2Fen%3E+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E+%22English%22+.%0A%0A&shapesFormat=text%2Fturtle&resource=%40prefix+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E+.%0A%40prefix+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E+.%0A%40prefix+vcard%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23%3E+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FJane_Doe%3E+a+schema%3APerson+%3B%0A%09schema%3Aname+%22Janet%22+.%0A%0A%3Chttp%3A%2F%2Fexample.com%2FJohn_Doe%3E+a+schema%3APerson+%3B%0A%09schema%3Aname+%22John+Doe%22+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FdigitalObjectIdentifier%3E+%22https%3A%2F%2Ffoo.bar%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23anyURI%3E+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FhasAttribute%3E+%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FChronicKidneyDisease%3E+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FoddsRatioHigh%3E+%22.9%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FoddsRatioLow%3E+%22.2%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FpValue%3E+%220.5%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E%2C+%22.7%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09%3Chttp%3A%2F%2Fid.mazetx.com%2Fmio%2FstandardError%3E+%22.1%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23float%3E+%3B%0A%09schema%3Aage+18+%3B%0A%09schema%3AbirthDate+%222022-06-24%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23date%3E+%3B%0A%09schema%3Aknows+%5B%0A%09%09%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+schema%3APerson+%3B%0A%09%5D%2C+%3Chttp%3A%2F%2Fexample.com%2FJane_Doe%3E+%3B%0A%09vcard%3Alanguage+%3Chttp%3A%2F%2Flexvo.org%2Fid%2Fiso639-1%2Fen%3E+%3B%0A%09foaf%3Agender+%22Male%22+.%0A%0A&resourceFormat=text%2Fturtle&resourcePrefixes=schema%2Cfoaf%2Cvcard&selectedResource=http%3A%2F%2Fexample.com%2FJohn_Doe&components=material&disableEditorChoice=false&nesting=inline&grouping=vaadin+accordion&labs=%7B%7D) to the example I'm working on.

You'll notice that the IRI for the shape I define is `http://example.com/GWASTraitAssociationShape`, that the target class is `http://id.mazetx.com/mio/GWASTraitAssociation`, and that I don't include any sample instances data.

However, the data I enter into the form is rendered as properties attached to `<http://example.com/John_Doe> a schema:Person ;`...

What I was hoping to do is clear out all the triples from the `schema:Person` example so that the generated form data is a valid shape. So if I would expect to see something like:

```turtle
_:b0 a <http://example.com/GWASTraitAssociationShape> ;
	<http://id.mazetx.com/mio/hasAttribute> <http://id.mazetx.com/mio/AmyotrophicLateralSclerosis> ;
	<http://id.mazetx.com/mio/digitalObjectIdentifier> "http://mygwasstudy.com"^^xsd:anyURI ;
	<http://id.mazetx.com/mio/pValue> "0.0000123"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioLow> ".1"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioHigh> ".4"^^xsd:float ;
	<http://id.mazetx.com/mio/standardError> ".09"^^xsd:float .
```

Or perhaps if I included an initial instance in my shape of `<http://example.com/study1> a <http://example.com/GWASTraitAssociationShape>` then the generated example would be

```turtle
<http://example.com/GWASTraitAssociationShape> a <http://example.com/GWASTraitAssociationShape> ;
	<http://id.mazetx.com/mio/hasAttribute> <http://id.mazetx.com/mio/AmyotrophicLateralSclerosis> ;
	<http://id.mazetx.com/mio/digitalObjectIdentifier> "http://mygwasstudy.com"^^xsd:anyURI ;
	<http://id.mazetx.com/mio/pValue> "0.0000123"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioLow> ".1"^^xsd:float ;
	<http://id.mazetx.com/mio/oddsRatioHigh> ".4"^^xsd:float ;
	<http://id.mazetx.com/mio/standardError> ".09"^^xsd:float .
```

Does that make sense?

**Comment by tpluscode** [comment]
Sorry for coming back late. As it happens, I initially misunderstood you question. 🤦 

You're right to observe that the usage is not perfect regarding the graphs and how the resources and shapes are selected for the form.

That said, you can always clear or modify the data graph yourself. However, that still keeps the URI information and I notice in your case that it prompts recreates that `John_Doe` resource with a blank trait. You can get around that but it's awkward at best

Please see what I just pushed. A small change, so that when you clear the right hand side editor
